my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
   path('admin/', admin.site.urls),
   path('polls/', include('polls.urls', namespace='polls')),
]

my_blog/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
   path('questions/', views.question_list, name='question_list'),
]
urlpatterns = [
   path('', views.question_list, name='question_list'),
   path('<int:question_id>/', views.question_detail, name='question_detail'),

]

my_blog/tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import home_view

urlpatterns = [
   path('', home_view),
   path('admin/', admin.site.urls),
   path('polls/', include('polls.urls', namespace='polls')),
]

my_blog/polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200, null=True)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.TextField(max_length=200)
    def __str__(self):
        return self.answer

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    def __str__(self):
        return self.choice_text

my_blog/polls/views.py
from .models import Question
from django.shortcuts import render, get_object_or_404

def question_list(request):
   questions = Question.objects.all()
   return render(request, 'polls/question_list.html', {'questions': questions})

def question_detail(request, question_id):
   question = get_object_or_404(Question, pk=question_id)
   return render(request, 'polls/question_detail.html', {'question': question})

my_blog/tutorial/views.py
from django.shortcuts import render

def home_view(request):
    #print(request)
    #print(request.user)

    return render(request, 'home.html')

my_blog/polls/templates/polls/question_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
<table>
    <tr>
        <th>pk</th>
        <th>question_text</th>
        <th>pub_date</th>
    </tr>
    <tr>
        <td>{{question.pk}}</td>
        <td>{{question}}</td>
        <td>{{question.pub_date}}</td>
        <td>{{question.votes}}</td>
    </tr>   
</table>

my_blog/polls/templates/polls/question_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
<table>
    <tr>
        <th>pk</th>
        <th>question_text</th>
        <th>pub_date</th>
    </tr>
    {% for question in question %}
        <tr>
            <td>{{question.pk}}</td>
            <td><a href="{% url 'question_detail' question.id %}">{{question}}</td>
            <td>{{question.pub_date}}</td>
        </tr>
    {% endfor %}


</table>

my_blog/polls/templates/question_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
<table>
    <tr>
        <th>pk</th>
        <th>question_text</th>
        <th>pub_date</th>
    </tr>
    <tr>
        <td>{{question.pk}}</td>
        <td>{{question}}</td>
        <td>{{question.pub_date}}</td>
        <td>{{question.votes}}</td>
    </tr>   
</table>

my_blog/polls/templates/question_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
<table>
    <tr>
        <th>pk</th>
        <th>question_text</th>
        <th>pub_date</th>
    </tr>
    {% for question in question %}
        <tr>
            <td>{{question.pk}}</td>
            <td><a href="{% url 'queston_detail' question.id %}">{{question}}</td>
            <td>{{question.pub_date}}</td>
        </tr>
    {% endfor %}


</table>

my_blog/templates/home.html
<h1> Strona główna </h1>

<!-- {{ user.is_authenticated }} -->

{% if user.is_authenticated %}
   <p>Cześć {{ user }}</p>
{% else %}
     <p>Nie jestes zalogowany</p>

{% endif %}
<button><a href="{% url 'polls:question_list'%}">Pytania</a></button>

my_blog/templates/polls/question_detail.html
<h1>{{ question.question_text }}</h1>
<h1>{{ question.pub_date }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <ul>
       <li>{{ choice.choice_text }} ({{ choice.votes }}) </li>
    </ul>
{% endfor %}
</ul>
<ul>
{% for answer in question.answer_set.all %}
    <ul>
       <li>{{ answer.answer_text }} </li>
    </ul>
{% endfor %}
</ul>open

my_blog/templates/polls/question_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div>
    <table>
        <tr>
            <th>Id pytania</th>
            <th>Treść</th>
            <th>Data publikacji</th>
        </tr>
        {% for question in questions %}
            <tr>
                <td>{{ question.id }}</td>
                <td><a href="{% url 'polls:question_detail' question.id %}">

                {{ question.question_text }}</a>
                </td>
                <td>{{question.pub_date}}</td>
                <td>{{question.type}}</td>
            </tr>
        {% endfor %}
    </table>
</div>
</body>
</html>